apiVersion: v1
kind: Service
metadata:
  name: temporal-worker-health
  labels:
    app: temporal-worker
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: health
  selector:
    app: temporal-worker
